### PR TITLE
leave should be a session event

### PR DESCRIPTION
**Pull request by evanlucas**
This must have gotten lost in the transition from chat events to
session events. The `leave` event is expected to be sent as a chat
session event not a chat client event.

### CODE REVIEW

**Comment by nubs** [comment]
LGTM, can you tack on a version bump as well so that we can update MC/plugin to require the new version

**Comment by evanlucas** [comment]
Done

**Comment by nubs** [comment]
LGTM

**Comment by evanlucas** [comment]
In all reality, these really should be semver major though as it is a breaking change.

**Comment by nubs** [comment]
We're before 1.0.0 which means semver doesn't define anything at all about the changes between versions

**Comment by evanlucas** [comment]
Good point

**Pull request merged**
